all:
	gcc -o cachesize.out cache.c -lm
	gcc -o forkspeed.out fork.c -lm
	gcc -o pipespeed.out pipe.c -lm
1:
	gcc -o cachesize.out cache.c -lm
2:
	gcc -o forkspeed.out fork.c -lm
3:
	gcc -o pipespeed.out pipe.c -lm
clean:
	rm *.out
